In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('users.csv')
df.head()

,id,firstName,lastName,maidenName,age,gender,email,phone,username,password,...,address,macAddress,university,bank,company,ein,ssn,userAgent,crypto,role
0,1,Emily,Johnson,Smith,29,female,emily.johnson@x.dummyjson.com,+81 965-431-3024,emilys,emilyspass,...,"{'address': '626 Main Street', 'city': 'Phoeni...",47:fa:41:18:ec:eb,University of Wisconsin--Madison,"{'cardExpire': '05/28', 'cardNumber': '3693233...","{'department': 'Engineering', 'name': 'Dooley,...",977-175,900-590-289,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
1,2,Michael,Williams,NaN,36,male,michael.williams@x.dummyjson.com,+49 258-627-6644,michaelw,michaelwpass,...,"{'address': '385 Fifth Street', 'city': 'Houst...",79:15:78:99:60:aa,Ohio State University,"{'cardExpire': '01/30', 'cardNumber': '3530633...","{'department': 'Support', 'name': 'Spinka - Di...",912-602,108-953-962,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
2,3,Sophia,Brown,NaN,43,female,sophia.brown@x.dummyjson.com,+81 210-652-2785,sophiab,sophiabpass,...,"{'address': '1642 Ninth Street', 'city': 'Wash...",12:a3:d3:6f:5c:5b,Pepperdine University,"{'cardExpire': '10/27', 'cardNumber': '6011212...","{'department': 'Research and Development', 'na...",963-113,638-461-822,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
3,4,James,Davis,NaN,46,male,james.davis@x.dummyjson.com,+49 614-958-9364,jamesd,jamesdpass,...,"{'address': '238 Jefferson Street', 'city': 'S...",10:7d:df:1f:97:58,University of Southern California,"{'cardExpire': '07/30', 'cardNumber': '5303440...","{'department': 'Support', 'name': 'Pagac and S...",904-810,116-951-314,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin
4,5,Emma,Miller,Johnson,31,female,emma.miller@x.dummyjson.com,+91 759-776-1614,emmaj,emmajpass,...,"{'address': '607 Fourth Street', 'city': 'Jack...",32:b9:7e:8d:f5:e8,Northeastern University,"{'cardExpire': '07/30', 'cardNumber': '5237188...","{'department': 'Human Resources', 'name': 'Gra...",403-505,526-210-885,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:9...,"{'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6...",admin

In [31]:
df.count()

id            208
firstName     208
lastName      208
maidenName     60
age           208
gender        208
email         208
phone         208
username      208
password      208
birthDate     208
image         208
bloodGroup    208
height        208
weight        208
eyeColor      208
hair          208
ip            208
address       208
macAddress    208
university    208
bank          208
company       208
ein           208
ssn           208
userAgent     208
crypto        208
role          208
dtype: int64

In [32]:
df.shape

(208, 28)

In [33]:
df.columns

Index(['id', 'firstName', 'lastName', 'maidenName', 'age', 'gender', 'email',
       'phone', 'username', 'password', 'birthDate', 'image', 'bloodGroup',
       'height', 'weight', 'eyeColor', 'hair', 'ip', 'address', 'macAddress',
       'university', 'bank', 'company', 'ein', 'ssn', 'userAgent', 'crypto',
       'role'],
      dtype='object')

In [34]:
df.dtypes

id              int64
firstName      object
lastName       object
maidenName     object
age             int64
gender         object
email          object
phone          object
username       object
password       object
birthDate      object
image          object
bloodGroup     object
height        float64
weight        float64
eyeColor       object
hair           object
ip             object
address        object
macAddress     object
university     object
bank           object
company        object
ein            object
ssn            object
userAgent      object
crypto         object
role           object
dtype: object

In [35]:
df.isnull().sum()

id              0
firstName       0
lastName        0
maidenName    148
age             0
gender          0
email           0
phone           0
username        0
password        0
birthDate       0
image           0
bloodGroup      0
height          0
weight          0
eyeColor        0
hair            0
ip              0
address         0
macAddress      0
university      0
bank            0
company         0
ein             0
ssn             0
userAgent       0
crypto          0
role            0
dtype: int64

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 28 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          208 non-null    int64
 1   firstName   208 non-null    object
 2   lastName    208 non-null    object
 3   maidenName  60 non-null     object
 4   age         208 non-null    int64
 5   gender      208 non-null    object
 6   email       208 non-null    object
 7   phone       208 non-null    object
 8   username    208 non-null    object
 9   password    208 non-null    object
 10  birthDate   208 non-null    object
 11  image       208 non-null    object
 12  bloodGroup  208 non-null    object
 13  height      208 non-null    float64
 14  weight      208 non-null    float64
 15  eyeColor    208 non-null    object
 16  hair        208 non-null    object
 17  ip          208 non-null    object
 18  address     208 non-null    object
 19  macAddress  208 non-null    object
 20  university  208 non-null    object
 21  bank        208 non-null    object
 22  company     208 non-null    object
 23  ein         208 non-null    object
 24  ssn         208 non-null    object
 25  userAgent   208 non-null    object
 26  crypto      208 non-null    object
 27  role        208 non-null    object
dtypes: float64(2), int64(2), object(24)
memory usage: 45.6+ KB

In [38]:
df.describe()

               id         age      height      weight
count  208.000000  208.000000  208.000000  208.000000
mean   104.500000   33.139423  175.720240   75.038606
std     60.188592    5.544269   14.119984   14.090775
min      1.000000   23.000000  150.250000   50.100000
25%     52.750000   29.000000  164.187500   62.547500
50%    104.500000   32.000000  177.430000   75.985000
75%    156.250000   36.000000  186.960000   86.992500
max    208.000000   46.000000  199.810000   99.540000

In [39]:
for col in ['gender', 'bloodGroup', 'role', 'eyeColor']:
    print(df[col].value_counts())
    print('************************')

gender
female    106
male      102
Name: count, dtype: int64
************************
bloodGroup
O-     31
B-     31
AB-    29
AB+    29
B+     25
O+     22
A+     21
A-     20
Name: count, dtype: int64
************************
role
user         193
moderator     10
admin          5
Name: count, dtype: int64
************************
eyeColor
Brown     35
Hazel     34
Green     28
Blue      24
Gray      24
Violet    22
Red       21
Amber     20
Name: count, dtype: int64
************************