In [159]:
import pandas as pd
import numpy as np

In [160]:
# Load the file students.csv and make sure Score Date is parsed as datetime.
df = pd.read_csv('students.csv', parse_dates=['Score Date'])
df

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6     Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [161]:
df.dtypes

Student ID             int64
Name                  object
Age                    int64
Grade                float64
Subject               object
City                  object
Passed                  bool
Score Date    datetime64[ns]
dtype: object

In [162]:
# Print the shape, columns list, and data types of the DataFrame.
df.shape

(9, 8)

In [163]:
df.columns

Index(['Student ID', 'Name', 'Age', 'Grade', 'Subject', 'City', 'Passed',
       'Score Date'],
      dtype='object')

In [164]:
df.dtypes

Student ID             int64
Name                  object
Age                    int64
Grade                float64
Subject               object
City                  object
Passed                  bool
Score Date    datetime64[ns]
dtype: object

In [165]:
# Show the first 7 rows and the last 3 rows.
df.head(7)

   Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2    Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3    Omar   19   65.0       Math        Giza   False 2025-01-20
3           4    Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5  Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6    Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7    Yara   30   89.0       Math       Cairo    True        NaT

In [166]:
df.tail(3)

   Student ID     Name  Age  Grade    Subject   City  Passed Score Date
6           7     Yara   30   89.0       Math  Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12

In [167]:
pd.concat([df.head(7), df.tail(3)])

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6     Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7     Yara   30   89.0       Math       Cairo    True        NaT
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [168]:
# Show how many missing values in each column.
df.isna().sum()

Student ID    0
Name          0
Age           0
Grade         1
Subject       0
City          0
Passed        0
Score Date    1
dtype: int64

In [169]:
# What is the average, minimum, and maximum Grade?
df['Grade'].describe()

count     8.000000
mean     76.375000
std      12.905564
min      55.000000
25%      70.250000
50%      75.000000
75%      88.250000
max      92.000000
Name: Grade, dtype: float64

In [170]:
# How many unique cities are there? List them
print(df['City'].nunique())
print(df['City'].unique())

4
['Cairo' 'Alexandria' 'Giza' 'Mansoura']

In [171]:
# Use value_counts() to show how many students per Subject.
df['Subject'].value_counts().rename('Students count').reset_index()

     Subject  Students count
0       Math               3
1  Chemistry               3
2    Physics               2
3    English               1

In [172]:
# Select only the columns: Name, Grade, Subject, City.
df[['Name', 'Grade', 'Subject', 'City']]

      Name  Grade    Subject        City
0    Ahmed   88.0       Math       Cairo
1     Sara   92.0    Physics  Alexandria
2     Omar   65.0       Math        Giza
3     Lina   78.0  Chemistry       Cairo
4   Khaled   55.0    Physics    Mansoura
5     Nour    NaN    English  Alexandria
6     Yara   89.0       Math       Cairo
7  Mohamed   72.0  Chemistry        Giza
8  Mohamed   72.0  Chemistry        Giza

In [173]:
# Show all students who Passed and have Grade ≥ 85.
df[(df['Passed'] == True) & (df['Grade'] >= 85)]

   Student ID   Name  Age  Grade  Subject        City  Passed Score Date
0           1  Ahmed   25   88.0     Math       Cairo    True 2025-01-15
1           2   Sara   32   92.0  Physics  Alexandria    True 2025-02-10
6           7   Yara   30   89.0     Math       Cairo    True        NaT

In [174]:
# Show students whose Name contains the letter "a" or "A" (case insensitive).
df[df['Name'].str.contains('a', case=False)]

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [175]:
# Show students in Cairo or Alexandria with Grade < 80.
df[(df['City'].isin(['Cairo', 'Alexandria'])) & (df['Grade'] < 80)]

   Student ID  Name  Age  Grade    Subject   City  Passed Score Date
3           4  Lina   28   78.0  Chemistry  Cairo    True 2025-03-05

In [176]:
# Show students with Grade between 80 and 90 (inclusive).
df[df['Grade'].between(80,90)]

   Student ID   Name  Age  Grade Subject   City  Passed Score Date
0           1  Ahmed   25   88.0    Math  Cairo    True 2025-01-15
6           7   Yara   30   89.0    Math  Cairo    True        NaT

In [177]:
# Using .loc, change Khaled's grade from 55 to 68.
df.loc[df['Name'] == 'Khaled', 'Grade'] = 68
df

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   68.0    Physics    Mansoura   False 2025-02-28
5           6     Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [178]:
# Add a new column Is_Excellent that is True if Grade ≥ 90, False otherwise (vectorized).
df['Is_Excellent'] = df['Grade'] >= 90
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False
5,6,Nour,22,NaN,English,Alexandria,True,2025-01-10,False
6,7,Yara,30,89.0,Math,Cairo,True,NaT,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False

In [179]:
# Fill missing Grade values with the average Grade.
df['Grade'] = df['Grade'].fillna(df['Grade'].mean())
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False
6,7,Yara,30,89.0,Math,Cairo,True,NaT,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False

In [180]:
# Fill missing Score Date values with the most common date (mode).
df['Score Date'] = df['Score Date'].fillna(df['Score Date'].mode()[0])
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False

In [181]:
# Add a new column Final_Grade = Grade + 5 (bonus points).
df['Final_Grade'] = df['Grade'] + 5
df.head()

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0

In [182]:
# Create a column Grade_Category using pd.cut with bins:
    # 0–69 → "Fail"
    # 70–79 → "Average"
    # 80–89 → "Good"
    # 90–100 → "Excellent"
df['Grade_Category'] =  pd.cut(df['Grade'], bins=[0,70,80,90,100], 
                               labels=['Fail', 'Average', 'Good', 'Excellent'])
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0,Fail
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [183]:
# Remove the column Student ID.
df = df.drop('Student ID', axis=1)
df.head()

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
2,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
4,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0,Fail

In [ ]:
# •Keep only students who Passed.
df = df[df['Passed'] == True]
df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [ ]:
# Sort the DataFrame by Grade descending.
df.sort_values('Grade', ascending=False)

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [ ]:
# Sort by City ascending, then inside each city sort by Grade descending.
df.sort_values(['City', 'Grade'], ascending=[True, False])

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [ ]:
# Add a column Rank that ranks students by Grade (1 = highest, handle ties with 'min').
df['Rank'] = df['Grade'].rank(ascending = False, method = 'min')
df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average,4.0
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0

In [ ]:
# •Show the top 4 students with the highest grades (use nlargest).
df['Grade'].nlargest(4)

1    92.0
6    89.0
0    88.0
3    78.0
Name: Grade, dtype: float64

In [ ]:
# •Show the 3 youngest students (use nsmallest on Age).
df['Age'].nsmallest(3)

5    22
0    25
7    27
Name: Age, dtype: int64

In [ ]:
# •Find the student(s) with the highest Grade and show their Name and Grade.
df[df['Grade'] == df['Grade'].max()][['Grade', 'Name']]

   Grade  Name
1   92.0  Sara

In [ ]:
# •After filling missing grades, recalculate the average Grade per Subject.
df['Grade'] = df['Grade'].fillna(df['Grade'].mean())
df.groupby('Subject')['Grade'].mean()

Subject
Chemistry    74.0
English      78.0
Math         88.5
Physics      92.0
Name: Grade, dtype: float64

In [ ]:
# •Create a new column City_Avg that shows the average grade of each student's city (using transform).
df['City_Avg'] = df.groupby('City')['Grade'].transform('mean')
df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank,City_Avg
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0,85.0
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0,85.0
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average,4.0,85.0
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0,85.0
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0,85.0
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0,72.0
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0,72.0

In [202]:
# •Show the subject with the highest average grade.
print(df.groupby('Subject')['Grade'].mean().idxmax())
print(df.groupby('Subject')['Grade'].mean().max())

Physics
92.0